name: jamar
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  carousel_pro: ^1.0.0
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  provider: ^4.3.2
  transparent_image: ^1.0.0
  flutter_spinkit: ^4.1.2
  flutter_typeahead: ^1.8.8
  uuid: ^2.2.2
  stripe_payment: ^1.0.8
  flutter_svg: ^0.19.1
  mpesa_flutter_plugin: ^1.0.0
  firebase_database: ^4.1.1
  firebase_storage: ^4.0.1
  google_sign_in: ^4.5.5
  image_picker: ^0.6.7
  flutter_local_notifications: ^3.0.0
  timeago: ^2.0.28
  firebase_core: "^0.5.0+1"
  flutter_multiple_image_picker: ^0.0.1
  firebase_user_stream: ^1.1.0
  geolocator: ^6.1.1
  google_maps_flutter: ^1.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/fast_food_cart.jpg
    - assets/images/cart_empty.jpg
    - assets/images/cart_empty.png
    - assets/images/no_internet.jpeg
    - assets/images/avatar.png
    - assets/images/girlies_logo.png
    - assets/images/empty.png
    - assets/images/facebook.png
    - assets/images/google_logo.png
    - assets/images/twitter.png
    - assets/images/girlies_text.png
    - assets/images/girlies_text_colored.png
    - assets/images/ic_launcher.png
    - assets/images/girlies_text_small.png
    - assets/images/girlies_text_support.png
    - assets/images/no_internet_access.png
    - assets/images/      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
